name: CICD
on: [push]
jobs:

  DockerHub:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - 
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1

        with:
          username: gilapop
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: gilapop/gender-api:latest
          cache-from: type=registry,ref=gilapop/gender-api:buildcache
          cache-to: type=registry,ref=gilapop/gender-api:buildcache,mode=max

  Google:
    runs-on: ubuntu-latest
    steps:
    - 
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - 
      name: Checkout
      uses: actions/checkout@v2

    - 
      name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - 
      name: 'Use gcloud CLI'
      run: 'gcloud info'